# Generated by Django 3.1.3 on 2020-11-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSec1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec1_title', models.CharField(max_length=100)),
                ('sec1_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSec2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec2_title', models.CharField(max_length=100)),
                ('sec2_desc', models.TextField()),
                ('sec2_dynamic_title', models.CharField(max_length=100)),
                ('sec2_dynamic_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutSec3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec3_title', models.CharField(max_length=100)),
                ('sec3_desc', models.TextField()),
                ('sec3_dynamic_title', models.CharField(max_length=100)),
                ('sec3_dynamic_desc', models.TextField()),
                ('sec3_dynamic_image', models.ImageField(upload_to='Images/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSec4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec4_title', models.CharField(max_length=100)),
                ('sec4_dynamic_value', models.IntegerField()),
                ('sec4_dynamic_title', models.CharField(max_length=100)),
                ('sec4_dynamic_desc', models.ImageField(upload_to='Images/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSec5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec5_title', models.CharField(max_length=100)),
                ('sec5_desc', models.TextField()),
                ('sec5_dynamic_desc', models.TextField()),
                ('sec5_dynamic_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AboutSec6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec6_title', models.CharField(max_length=100)),
                ('sec6_dynamic_image', models.ImageField(upload_to='Images/')),
                ('sec6_dynamic_desc', models.TextField()),
                ('sec6_dynamic_name_person', models.CharField(max_length=100)),
                ('sec6_dynamic_profession', models.CharField(max_length=100)),
            ],
        ),
    ]
