# Generated by Django 2.2.17 on 2020-11-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0002_aboutsec2_sec2_dynamic_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsec4',
            name='sec4_dynamic_desc',
        ),
        migrations.AddField(
            model_name='aboutsec4',
            name='sec4_dynamic_image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/'),
        ),
        migrations.AddField(
            model_name='aboutsec5',
            name='sec5_dynamic_image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='aboutsec1',
            name='sec1_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutsec2',
            name='sec2_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsec3',
            name='sec3_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsec4',
            name='sec4_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsec6',
            name='sec6_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
