# Generated by Django 2.2.17 on 2020-11-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0003_auto_20201124_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsec4',
            name='sec4_dynamic_desc',
            field=models.TextField(default=2020),
            preserve_default=False,
        ),
    ]
