# Generated by Django 2.2.17 on 2020-11-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0004_aboutsec4_sec4_dynamic_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsec2',
            name='sec2_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsec3',
            name='sec3_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsec5',
            name='sec5_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsec5',
            name='sec5_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsec6',
            name='sec6_dynamic_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
