# Generated by Django 2.2.17 on 2020-11-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0005_auto_20201124_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsec2',
            name='sec2_dynamic_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
