# Generated by Django 2.2.17 on 2020-11-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0006_auto_20201124_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teamsec1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec1_title', models.CharField(blank=True, max_length=100, null=True)),
                ('sec1_image', models.ImageField(upload_to='Images/')),
            ],
        ),
        migrations.CreateModel(
            name='Teamsec2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec2_title', models.CharField(blank=True, max_length=100, null=True)),
                ('sec2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sec2_image', models.ImageField(upload_to='Images/')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutsec6',
            name='sec6_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
