# Generated by Django 2.2.17 on 2020-11-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0007_auto_20201124_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsec2',
            name='sec2_dynamic_icon_choice',
            field=models.CharField(choices=[('COM', 'Computer'), ('SUP', 'Support'), ('PRO', 'Process'), ('DEV', 'Development')], default=2020, max_length=3),
            preserve_default=False,
        ),
    ]
