# Generated by Django 2.2.17 on 2020-11-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0008_aboutsec2_sec2_dynamic_icon_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsec2',
            name='sec2_desc',
        ),
        migrations.RemoveField(
            model_name='aboutsec2',
            name='sec2_title',
        ),
    ]
