# Generated by Django 2.2.17 on 2020-11-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0012_auto_20201124_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsec3',
            name='sec3_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsec3',
            name='sec3_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
