# Generated by Django 2.2.17 on 2020-11-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0013_auto_20201124_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsec2',
            name='sec2_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsec2',
            name='sec2_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
