# Generated by Django 2.2.17 on 2020-11-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0014_auto_20201124_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsec1',
            name='sec1_image',
            field=models.ImageField(upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='aboutsec2',
            name='sec2_dynamic_image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='teamsec1',
            name='sec1_title',
            field=models.CharField(default=2020, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamsec2',
            name='sec2_name',
            field=models.CharField(default=2020, max_length=100),
            preserve_default=False,
        ),
    ]
