# Generated by Django 2.2.17 on 2020-11-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0016_auto_20201125_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsec2',
            name='sec2_dynamic_icon_choice',
            field=models.CharField(choices=[('COM', 'computer'), ('SUP', 'support'), ('PRO', 'process'), ('DEV', 'development')], max_length=3),
        ),
    ]
