# Generated by Django 2.2.17 on 2020-11-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0018_auto_20201125_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsec2',
            name='sec2_dynamic_icon_choice',
            field=models.CharField(choices=[('computer', 'computer'), ('support', 'support'), ('process', 'process'), ('development', 'development')], max_length=11),
        ),
    ]
