# Generated by Django 2.2.17 on 2020-11-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0019_auto_20201125_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsec4',
            name='sec4_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
