# Generated by Django 2.2.17 on 2020-11-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0023_auto_20201125_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSec1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec1_title', models.CharField(max_length=100)),
                ('sec1_image', models.ImageField(upload_to='Images/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSec2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec2_title', models.CharField(blank=True, max_length=100, null=True)),
                ('sec2_desc', models.TextField(blank=True, null=True)),
                ('sec2_dynamic_image', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('sec2_dynamic_title', models.CharField(max_length=100)),
                ('sec2_dynamic_desc', models.TextField()),
                ('sec2_dynamic_icon_choice', models.CharField(choices=[('computer', 'computer'), ('support', 'support'), ('process', 'process'), ('development', 'development')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='AboutSec3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec3_title', models.CharField(blank=True, max_length=100, null=True)),
                ('sec3_desc', models.TextField(blank=True, null=True)),
                ('sec3_dynamic_title', models.CharField(max_length=100)),
                ('sec3_dynamic_desc', models.TextField()),
                ('sec3_dynamic_image', models.ImageField(upload_to='Images/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSec4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec4_title', models.CharField(blank=True, max_length=100, null=True)),
                ('sec4_image', models.ImageField(blank=True, upload_to='')),
                ('sec4_dynamic_value', models.IntegerField()),
                ('sec4_dynamic_title', models.CharField(max_length=100)),
                ('sec4_dynamic_desc', models.TextField()),
                ('sec4_dynamic_image', models.ImageField(blank=True, null=True, upload_to='Images/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSec5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec5_title', models.CharField(blank=True, max_length=100, null=True)),
                ('sec5_desc', models.TextField(blank=True, null=True)),
                ('sec5_dynamic_desc', models.TextField()),
                ('sec5_dynamic_title', models.CharField(max_length=100)),
                ('sec5_dynamic_image', models.ImageField(blank=True, null=True, upload_to='Images/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSec6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec6_title', models.CharField(blank=True, max_length=100, null=True)),
                ('sec6_dynamic_image', models.ImageField(upload_to='Images/')),
                ('sec6_dynamic_desc', models.TextField(blank=True, null=True)),
                ('sec6_dynamic_name_person', models.CharField(max_length=100)),
                ('sec6_dynamic_profession', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teamsec1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec1_title', models.CharField(max_length=100)),
                ('sec1_image', models.ImageField(upload_to='Images/')),
            ],
        ),
        migrations.CreateModel(
            name='Teamsec2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec2_title', models.CharField(blank=True, max_length=100, null=True)),
                ('sec2_name', models.CharField(max_length=100)),
                ('sec2_image', models.ImageField(upload_to='Images/')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutModel',
        ),
    ]
