# Generated by Django 2.2.17 on 2020-11-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0025_auto_20201125_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcarousel',
            name='is_active',
            field=models.BooleanField(default=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='aboutmain',
            name='is_active',
            field=models.BooleanField(default=True, null=True, unique=True),
        ),
    ]
