# Generated by Django 2.2.17 on 2020-11-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0027_remove_aboutcarousel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teamsec1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, null=True, unique=True)),
                ('sec1_title', models.CharField(max_length=100)),
                ('sec1_image', models.ImageField(upload_to='Images/')),
            ],
        ),
        migrations.CreateModel(
            name='Teamsec2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec2_title', models.CharField(max_length=100)),
                ('sec2_name', models.CharField(max_length=100)),
                ('sec2_image', models.ImageField(upload_to='Images/')),
            ],
        ),
    ]
