# Generated by Django 2.2.17 on 2020-11-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0028_teamsec1_teamsec2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionVision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_heading', models.CharField(max_length=100)),
                ('top_bg_image', models.ImageField(upload_to='Images/')),
            ],
        ),
        migrations.AddField(
            model_name='aboutmain',
            name='sec1_inner1_icon_choice',
            field=models.CharField(choices=[('computer', 'computer'), ('support', 'support'), ('process', 'process'), ('development', 'development')], default=2020, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmain',
            name='sec1_inner1_image',
            field=models.ImageField(null=True, upload_to='Images/'),
        ),
        migrations.AddField(
            model_name='aboutmain',
            name='sec1_inner2_icon_choice',
            field=models.CharField(choices=[('computer', 'computer'), ('support', 'support'), ('process', 'process'), ('development', 'development')], default=2020, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmain',
            name='sec1_inner2_image',
            field=models.ImageField(null=True, upload_to='Images/'),
        ),
        migrations.AddField(
            model_name='aboutmain',
            name='sec1_inner3_icon_choice',
            field=models.CharField(choices=[('computer', 'computer'), ('support', 'support'), ('process', 'process'), ('development', 'development')], default=2020, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmain',
            name='sec1_inner3_image',
            field=models.ImageField(null=True, upload_to='Images/'),
        ),
        migrations.AddField(
            model_name='aboutmain',
            name='sec1_inner4_icon_choice',
            field=models.CharField(choices=[('computer', 'computer'), ('support', 'support'), ('process', 'process'), ('development', 'development')], default=2020, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmain',
            name='sec1_inner4_image',
            field=models.ImageField(null=True, upload_to='Images/'),
        ),
        migrations.AddField(
            model_name='aboutmain',
            name='sec3_bg_image',
            field=models.ImageField(null=True, upload_to='Images/'),
        ),
    ]
