# Generated by Django 2.2.17 on 2020-11-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0029_auto_20201126_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmain',
            name='sec1_inner1_sub_desc',
            field=models.TextField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmain',
            name='sec1_inner2_sub_desc',
            field=models.TextField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmain',
            name='sec1_inner3_sub_desc',
            field=models.TextField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmain',
            name='sec1_inner4_sub_desc',
            field=models.TextField(default=2020),
            preserve_default=False,
        ),
    ]
