# Generated by Django 2.2.17 on 2020-11-26 09:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0031_aboutcarousel_sec5_inner_sub_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcarousel',
            name='sec2_inner_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutcarousel',
            name='sec5_inner_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutcarousel',
            name='sec5_inner_sub_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='sec1_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='sec1_inner1_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='sec1_inner1_sub_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='sec1_inner2_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='sec1_inner2_sub_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='sec1_inner3_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='sec1_inner3_sub_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='sec1_inner4_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='sec1_inner4_sub_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='sec2_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='sec3_inner1_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='sec3_inner2_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='sec3_inner3_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='sec3_inner4_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='sec4_inner1_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='sec4_inner2_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='sec4_inner3_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutmain',
            name='sec4_inner4_desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
