# Generated by Django 2.2.17 on 2020-11-26 12:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0032_auto_20201126_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_heading', models.CharField(max_length=100)),
                ('top_bg_image', models.ImageField(upload_to='Images/')),
                ('sec_title', models.CharField(max_length=100)),
                ('sec_desc', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
