# Generated by Django 2.2.17 on 2020-11-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0033_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True, null=True, unique=True),
        ),
    ]
