# Generated by Django 2.2.17 on 2020-11-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20201125_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictures',
            old_name='image',
            new_name='logo',
        ),
    ]
