# Generated by Django 2.2.17 on 2020-11-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20201126_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='pictures',
            name='is_active',
            field=models.BooleanField(default=True, null=True, unique=True),
        ),
    ]
